### ISSUE TITLE
a error about eigen

### ISSUE THREAD

**Issue by rafion1** [jaeyoungjo99/ELiMaLoc#1] opened 2024-12-22 10:35 UTC
Thank you for your work. I had this error when replicating your project: When I used the 2D Pose Estimate on rviz to give the initial pose, as shown in the figure, it was probably about the order conflict between eigen and the matrix：

**> ekf_localization: /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:281: void Eigen::PlainObjectBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<double, 27, 27>; Eigen::Index = long i
> t]: Assertion `(!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=
> axRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."' failed.
> [ekf_localization-2] process has died [pid 49927, exit code -6, cmd /home/ls/ELiMaLoc/devel/lib/ekf_localization/ekf_localization __name:=ekf_localization __log:=/home/ls/.ros/log/204bd360-bec4-11ef-a763-2f9e9caf465a/
> kf_localization-2.log].
> log file: /home/ls/.ros/log/204bd360-bec4-11ef-a763-2f9e9caf465a/ekf_localization-2*.log**

Have you encountered this problem before? If so, how was it resolved?
<img width="860" alt="1734863562709" src="https://github.com/user-attachments/assets/4fdc8dc9-334e-46af-aa3b-770eb29a6fb6" />

ps：my system is ubuntu20.04, ros version is noetic,eigen version is 3.3.7-2

**Comment by jaeyoungjo99** [comment] 2024-12-23 05:46
Thank you for your interest in my code.

In my computer environment (Ubuntu 20.04, Noetic),
I did not have any problems when I used the **roslaunch launch/ELiMaLoc.launch location:=kcity bag:=true** option.

However, since it seems to be an error regarding the 27x27 Eigen Matrix, it seems to be a problem with the **Eigen::Matrix<double, STATE_ORDER, STATE_ORDER> P_;** variable in ekf_algorithm.hpp.

I found a bug in ekf_algorithm.cpp https://github.com/jaeyoungjo99/ELiMaLoc/blob/f89294b3714f19cda3a94e8f49ccf17dbf635f23/src/app/localization/ekf_localization/src/ekf_algorithm.cpp#L336

There was an incorrect redefinition of the eigen matrix P_, which was fixed in the new commit f89294b in main branch.
And I also added initial position for each scenario in README.md file

If the issue is resolved with a new commit, please reply. 

Thank you for reporting problem.

**Comment by rafion1** [comment] 2024-12-25 00:59
thanks. it is ok

**Closed as completed** 2024-12-25 01:49 UTC
